services:
  - type: web
    name: notes-mern-api
    runtime: node
    rootDir: backend
    plan: free
    autoDeploy: true
    buildCommand: npm install --include=dev && npm run build
    startCommand: npm run start
    healthCheckPath: /
    envVars:
      - key: NODE_ENV
        value: production
      - key: FRONTEND_URL
        value: https://raghavainotes-mern.onrender.com
      - key: MONGO_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: GEMINI_API_KEY
        sync: false

  - type: web
    name: notes-mern-frontend
    runtime: static
    rootDir: frontend
    buildCommand: npm install && npm run build
    staticPublishPath: dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: VITE_API_URL
        value: https://notes-mern-api.onrender.com/api
